[project]
name = "elmo_geo"
version = "0.1"
description = "Environmental Land Management Geospatial Analysis"
readme = "README.md"
dependencies = [
    "apache-sedona==1.4.1",
    "beautifulsoup4",
    "contextily",
    "databricks-cli",
    "databricks-sdk",
    "esridump",
    "geopandas",
    "mapclassify",
    "numpy",
    "osdatahub",
    "osmnx",
    "pandas<=1.5.3",
    "pyarrow",
    "pydantic",
    "pyogrio",
    "pyspark==3.3.2",
    "rich",
    "rasterio",
    "rioxarray",
    "seaborn",
    "sentinelsat",
    "shapely",
    "xarray",
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
exclude = ["tests"]

[project.optional-dependencies]
dev = [
    "ruff<=0.1.15",
    "pip-tools",
    "pytest",
    "dbx",
    "ipykernel",
    "ipython",
    "ipywidgets",
]

[project.urls]
homepage = "https://github.com/Defra-Data-Science-Centre-of-Excellence/elmo-geo"


[build-system]
requires = ["setuptools>=64.0.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
python_files = "tests/*.py"
markers = ["without_cluster: test that can be run without being attached to databricks cluster"]


[tool.ruff]
line-length = 160
unsafe-fixes = false

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"notebooks/*" = []
"elmo_geo/*" = []
"tests/*" = []

[tool.ruff.lint]
select = []
ignore = ["D203", "D212", "COM812", "ISC001"]
