[tool.pytest.ini_options]
python_files="tests/test_*.py"
markers=[
  "without_cluster"  # test that can be run without being attached to databricks cluster
]

[tool.ruff]
line-length = 100
exclude = ["notebooks/**"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"notebooks/*" = []
