[tool.pytest.ini_options]
python_files = "tests/*.py"
markers = [
  "without_cluster: test that can be run without being attached to databricks cluster",
]

[tool.ruff]
line-length = 100
# unsafe-fixes = true

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]
"notebooks/*" = []

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  # Conflicts
  "D203",
  "D212",
  "COM812",
  "ISC001",
  # TODO notebooks
  "ARG002",
  "B018",
  "D101",
  "D102",
  "D107",
  "DTZ001",
  "DTZ005",
  "E402",
  "E722",
  "E741",
  "F811",
  "F821",
  "INP001",
  "N801",
  "PD008",
  "PD010",
  "PD011",
  "PGH004",
  "PLW2901",
  "PTH103",
  "PTH118",
  "PTH120",
  "PTH202",
  "RUF001",
  "S310",
  "T201",
  # TODO
  "A002",
  "ARG001",
  "ARG005",
  "ANN001",
  "ANN002",
  "ANN003",
  "ANN101",
  "ANN201",
  "ANN202",
  "ANN204",
  "B007",
  "B023",
  "B904",
  "BLE001",
  "D100",
  "D103",
  "D104",
  "D105",
  "D205",
  "D206",
  "D400",
  "D401",
  "D404",
  "D415",
  "D417",
  "E501",
  "ERA001",
  "FA100",
  "FBT001",
  "FBT002",
  "FBT003",
  "FIX002",
  "ISC003",
  "N802",
  "N803",
  "N806",
  "N812",
  "PERF203",
  "PD901",
  "PD003",
  "PLR0913",
  "PLR2004",
  "PTH102",
  "PTH107",
  "PTH110",
  "PTH123",
  "PTH207",
  "PYI041",
  "RET505",
  "S101",
  "S105",
  "S108",
  "S110",
  "S113",
  "S602",
  "S603",
  "S608",
  "SIM114",
  "SLF001",
  "TRY002",
  "TRY200",
  "TD002",
  "TD003",
]
