[tool.black]
line-length = 100
exclude = '''(
    \.eggs
  | \.git
  | \.mypy_cache
  | build
  | dist
  | .*.ipynb
)'''

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 100
per-file-ignores = "__init__.py:F401"