name: Deploy Documentation to GitHub Pages
on:
    push:
        branches: [main, master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - run: pip install -r requirements.txt
            - run: pip install .[docs]
            - run: mkdocs gh-deploy --force