name: Verify

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: https://raw.githubusercontent.com/databrickslabs/mosaic/main/.github/actions/scala_build/action.yml
      # - uses: https://raw.githubusercontent.com/databrickslabs/mosaic/main/.github/actions/python_build/action.yml
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - run: make install
      - run: |
          make fmt
          git add .
          git diff-index --quiet HEAD || git commit -m "make fmt"
      - run: make verify_gh
