name: Verify

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/databrickslabs/mosaic/blob/main/.github/workflows/build_main.yml
      - run: make install
      - run: make verify
