name: Verify

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
      - run: make install
      - uses: astral-sh/ruff-action@v2
      - run: ruff check .
      - run: ruff format . --check
      - uses: crate-ci/typos@master
      - uses: pavelzw/pytest-action
        with:
          pytest-args: "--markers 'no dbr'"
