name: Verify

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: databrickslabs/mosaic-actions/scala_build
      - uses: databrickslabs/mosaic-actions/python_build
      - run: make install
      - run: make verify
