name: Verify

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: databrickslabs/mosaic@build_main
      - run: make install
      - run: make verify
